### ISSUE TITLE
PROXY MODULE: error :  Get "https://localhost:9999/segment_3724023_.mp4": HeadersStreamDataDecompressFailure: cannot read frame

### ISSUE THREAD

**Issue by renyue0411** [thomaswpp/mpquic-sbd#2]
Hello，
I meet an error as shown in below when I ran astream client. 
It seems like quic-go's error, because when I ran this code without "-q“  and "-mp", it can run with no error.
It would be great if you help me figure it out.
<details><summary>Details</summary>
<p>

mpserver@mpserver:~/Desktop/mpquic-sbd/src$ python3 AStream/dist/client/dash_client.py -m "https://localhost:9999/output_dash.mpd" -p 'basic' -q -mp
2024-10-30 14:15:50,435 - dash_client.py:593 - INFO - Downloading MPD file https://localhost:9999/output_dash.mpd
https://localhost:9999/output_dash.mpd
2024-10-30 14:15:50,439 - dash_client.py:96 - INFO - Downloaded the MPD file
2024-10-30 14:15:50,439 - read_mpd.py:131 - INFO - Reading the MPD file
mpd format 1
2024-10-30 14:15:50,440 - read_mpd.py:237 - INFO - Found Video
2024-10-30 14:15:50,440 - read_mpd.py:239 - INFO - Retrieving Media
2024-10-30 14:15:50,440 - dash_client.py:602 - INFO - The DASH media has 1 video representations
2024-10-30 14:15:50,440 - dash_client.py:612 - CRITICAL - Started Basic-DASH Playback
2024-10-30 14:15:50,440 - dash_buffer.py:19 - INFO - Initializing the Buffer
2024-10-30 14:15:50,440 - dash_buffer.py:54 - INFO - VideoLength=20.066,segmentDuration=2.8665714285714285,MaxBufferSize=1,InitialBuffer(secs)=1,BufferAlph(secs)=1,BufferBeta(secs)=2
2024-10-30 14:15:50,440 - dash_buffer.py:62 - INFO - Changing state from INITIALIZED to INITIAL_BUFFERING at 0.0 Playback time 
2024-10-30 14:15:50,440 - dash_buffer.py:264 - INFO - BufferStats: EpochTime=0,CurrentPlaybackTime=0.0,CurrentBufferSize=0,CurrentPlaybackState=INITIAL_BUFFERING,Action=Starting,Bitrate=0
2024-10-30 14:15:50,440 - dash_buffer.py:229 - INFO - Starting the Player
2024-10-30 14:15:50,441 - dash_buffer.py:75 - INFO - Initialized player with video length 20.066
2024-10-30 14:15:50,456 - dash_buffer.py:264 - INFO - BufferStats: EpochTime=0,CurrentPlaybackTime=0.0,CurrentBufferSize=0,CurrentPlaybackState=INITIAL_BUFFERING,Action=Starting,Bitrate=0
[3724023]
2024-10-30 14:15:50,456 - dash_client.py:248 - INFO -  BASIC: Processing the segment 1
segment_number =1
dp_object.video[bitrate].start=1
2024-10-30 14:15:50,456 - dash_client.py:331 - INFO - BASIC: Segment URL = https://localhost:9999/segment_3724023_.mp4
2024/10/30 14:15:50 PROXY MODULE: created http2 QUIC client (MP: true, %!s(int=0))
2024/10/30 14:15:50 PROXY MODULE: error :  Get "https://localhost:9999/segment_3724023_.mp4": HeadersStreamDataDecompressFailure: cannot read frame
Traceback (most recent call last):
  File "AStream/dist/client/dash_client.py", line 628, in <module>
    sys.exit(main())
  File "AStream/dist/client/dash_client.py", line 613, in main
    start_playback_smart(dp_object, domain, "BASIC", DOWNLOAD, video_segment_duration)
  File "AStream/dist/client/dash_client.py", line 346, in start_playback_smart
    segment_size, segment_filename = download_segment(segment_url, file_identifier, download)
  File "AStream/dist/client/dash_client.py", line 137, in download_segment
    raise ValueError("invalid segment_size, connection dropped")
ValueError: invalid segment_size, connection dropped
</p>
</details>

**Comment by Zack-Tsang** [comment]
Hello, have you successfully installed the VM image provided by the author? I could not launch the VM on the KVM, could you give me some advice?
